# SITE SETUP
# Guide: https://docs.hugoblox.com/tutorial/
# Documentation: https://docs.hugoblox.com/
# This file is formatted using YAML syntax - learn more at https://learnxinyminutes.com/docs/yaml/

# Appearance
appearance:
  mode: light
  color: blue

# SEO
marketing:
  seo:
    site_type: Person
    description: 'Personal academic website'
  analytics: {}

# Site header
header:
  navbar:
    enable: true
    fixed_to_top: true
    show_search: false
    show_theme_chooser: false
    logo:
      text: "James Hope"

# Site footer
footer:
  copyright:
    notice: '© {year} Me'

# Localization
i18n:
  language: en
  content_dir: content
  i18n_dir: i18n
  default_content_language: en
  default_content_language_in_subdir: false
  enable_emoji: false
  enable_robots_txt: false
  build_drafts: false
  build_future: false
  build_expired: false
  enable_git_info: false
  enable_related_content: false
  enable_rss_link_in_feed: false
  enable_shortcodes: true
  enable_taxonomies: true
  enable_uglyurls: false
  enable_unsafe_markdown: false
  frontmatter:
    lastmod: [":fileModTime"]
    date: [":git", ":fileModTime"]
